name: application-deployment 

on:
 push: 
   branches: 
     - main

jobs: 
  continous-intergration-test: 
    runs-on: ubuntu:latest 

    steps: 
     - name: my-first-job 
       run: echo "My first job triggered by suhas"


