name: output

on: 
  workflow_dispatch:

jobs: 
  output_display_job:
    
    runs-on: ubuntu-latest 
    
    outputs:
       output_building: ${{steps.step1.outputs.message}}

    steps: 
      - name: building 
        id: step1
        run: |
             echo "message= The message is from the step1" >> $GITHUB_OUTPUT


      - name: output 
        run: echo "${{steps.step1.outputs.message}}"
  


  second_job:  
    needs: output_display_job
     
    runs-on: ubuntu-latest

    steps: 
       - name: variable_outputstage 
         run: echo "Referring the output of the other job - ${{needs.output_display_job.outputs.output_building}}"
