name: Relational-jobs 

on: 
  workflow_dispatch: 

   inputs: 
      username: 
        type: string 
        default: suhas 
        description: "Please give the username"     
        required: true
      
      environment: 
        type: choice 
        default: test 
        description: "The environment for deploy"
        required: true 
        options: 
          - test 
          - QA 
          - prod 

env: 
  DB_USERNAME: "my-db-mangodb" 
  DB_PASSWORD: "1234566778"


jobs: 
  job1: 
    runs-on: ubuntu-latest 

    steps: 
      - name: checking out the code
        uses: actions/checkout@v7 

      - name: verifing the variables 
        run: | 
          echo "The input variable is: ${{ inputs.environment }}" 
          echo "The input variable is: ${{ inputs.username }}"  
      
      - name: testng the exit 
        run: exit 1
  
  job2: 
    needs: job1 
    runs-on: ubuntu-latest 
    
    steps: 
      - name: verifing the variables 
        run: | 
          echo "The environment variable is $DB_USERNAME" 
          echo "The environment variable is $DB_PASSWORD"
      